# Generated by Django 3.2.13 on 2022-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220704_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=models.TextField(max_length=2500), max_length=150),
        ),
    ]
