# Generated by Django 3.2.13 on 2022-07-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='revised_on',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
