# Generated by Django 3.2.13 on 2022-07-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_comment_revised_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='revised_on',
        ),
    ]
